name: todoList 自动部署
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - uses: actions/setup-node@v3
        with:
          node-version: 20.13.1
      - run: pnpm install
      - run: pnpm run build_f
      - name: action-Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEVELOP_SECRET }}
          publish_branch: gh-pages
          publish_dir: ./dist
